CREATE DATABASE IF NOT EXISTS ims_finance;
USE ims_finance;

CREATE TABLE IF NOT EXISTS KONTRAK (
    KONTRAK_NO VARCHAR(20) PRIMARY KEY,
    CLIENT_NAME VARCHAR(100) NOT NULL,
    OTR DECIMAL(15, 2) NOT NULL,
    DP DECIMAL(15, 2) NOT NULL,
    JANGKA_WAKTU INT NOT NULL,
    BUNGA DECIMAL(5, 2) NOT NULL,
    POKOK_UTANG DECIMAL(15, 2) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS JADWAL_ANGSURAN (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    KONTRAK_NO VARCHAR(20) NOT NULL,
    ANGSURAN_KE INT NOT NULL,
    ANGSURAN_PER_BULAN DECIMAL(15, 2) NOT NULL,
    TANGGAL_JATUH_TEMPO DATE NOT NULL,
    PAID_STATUS BOOLEAN DEFAULT FALSE,
    PAID_DATE DATE NULL,
    FOREIGN KEY (KONTRAK_NO) REFERENCES KONTRAK(KONTRAK_NO) ON DELETE CASCADE
);
